//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnMobileContainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContentGallary
    {
        public int id { get; set; }
        public Nullable<int> contentId { get; set; }
        public Nullable<int> gallaryId { get; set; }
    
        public virtual tblContent tblContent { get; set; }
        public virtual tblGallary tblGallary { get; set; }
    }
}
